replicaCount: 1

namespace: monitoring

image:
  repository: "docker.io/${{ secrets.DOCKER_USERNAME }}/helloworld"
  tag: latest

service:
  type: LoadBalancer  # Expose service through LoadBalancer
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

probes:
  enabled: true
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    path: /readiness
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

serviceAccount:
  create: true
