apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: monitoring
spec:
  selector:
    app: helloworld
  ports:
    - port: 8080          # External port to expose the service
      targetPort: 8000    # Application's listening port inside the pod
      protocol: TCP
  type: LoadBalancer
