name: CI/CD Pipeline for HelloWorld

on:
  push:
    branches:
      - main

env:
  APP_NAME: "helloworld"
  AWS_REGION: "us-east-1"
  CLUSTER_NAME: "noise-dev"
  DOCKER_IMAGE: "docker.io/${{ secrets.DOCKER_USERNAME }}/$APP_NAME:${{ github.sha }}"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/helloworld:latest
          ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }}

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Deploy Application using Helm
      run: |
        helm upgrade --install ${{ env.APP_NAME }} ./helmchart \
          --namespace default \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/helloworld \
          --set image.tag=${{ github.sha }} \
          --create-namespace

    - name: Verify Deployment
      run: |
        kubectl get pods -n default
        kubectl describe deployment ${{ env.APP_NAME }} -n default
